### ISSUE TITLE
Discussion and Vote: baseUrl as a config option

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/the-spec#14]
As a design system creator using Pattern Lab, I want to better control the url behavior of Pattern Lab when hosted from a sub-directory.

---

This feature is proposed from the PL/Node team, [as already implemented in this PR](https://github.com/pattern-lab/patternlab-node/pull/130).  Like [Discussion & Vote: defaultPattern config option](#13) this PR is included here for functional understanding only, and is not necessarily the suggested implementation. I think that features should be up or down voted on their functional merit during these discussions, not the particular code that might serve as a reference.

I will be honest, however, in stating that I have not yet used this feature myself in a production environment. Feedback from the community would be welcome.

Timeline for this change is, in my opinion, not critical to 2.0.0 release.

Tagging `core` and `shared assets` due to this being an additional configuration option set in core that affects frontend.

This vote will close at noon central on June 15, 2016 or once both the PHP and Node representatives have voted.

/cc @pattern-lab/voting-members

**Comment by dmolsen** [comment]
I'm going to test this in PL/PHP. It doesn't seem like this should be a problem that requires fixing so I'm curious where the breakdown is.

**Comment by bmuenzenmeyer** [comment]
I apologize if it's a red herring too. I've never needed it either but it
didn't seem like it broke anything at the time.

I'd be fine with this not making it in unless the community responds
otherwise.  It was included this morning out of a desire for completeness
of reporting known differences.

**Comment by dmolsen** [comment]
This doesn't appear to be a problem in PL/PHP. There's a bug related to lineage but a `baseURL` option isn't necessary to address it. I build my paths in Core with `../../` in them so everything is relative. In this case the lineage path is going to break in the viewer vs. style guide but, again, doesn't need `baseURL` to fix.

This gets a 👎 from me because I think our output should be moveable without tweaking a config and rebuilding.

This doesn't mean you don't go to a release with this built-in. It's just that future work should endeavour to pull it back out.

**Comment by bmuenzenmeyer** [comment]
I am fine with :-1: until a time comes when someone can make a stronger case.
