### ISSUE TITLE
Question: Why does the spec call out Mustache as the de-facto template language?

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/the-spec#5]
`3.1. Mustache`

I have no problem with it - but it's a decision made in the spec.

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

Um… because the core templates and patterns are Mustache files? You don't have a problem that I highlight Markdown in the spec?

Similar to what I answered in the other issue... I expect that we all read in a common set of base files and spit out a common set of files. That should limit work. But maybe I'm making a big assumption. I've never written a spec before.

**Comment by bmuenzenmeyer** [comment]
I am fine with this.  It seems reasonable to me - especially so all ports can utilize existing stuff. When I wrote the question I was thinking it rather specific to mention this but not PHP, and then I realized the audience :P
