### ISSUE TITLE
Reconcile the spec with patternlab.io's "what it is" section

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/the-spec#6]
patternlab.io defines PL as:
- static site generator
- component library
- pattern starter kit
- viewport resizer
- annotation tool
- auto refresh tool
- page follow tool

However, the spec states:

```
2. General Functionality
  2.1. Pattern Generation
    2.1.1. Style Guide Page
    2.1.2. View All Pages
    2.1.3. Pattern Pages
  2.2. The Viewer page
```

I see either patternlab.io needing to change as the spec evolves, or the spec needs to be more inclusive of general functionality to be expected of ports.

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

The only things on the website list that aren't included in the spec are the auto-refresh and page follow stuff. That seems like it'll be platform-specific solutions. As for ports… the only functional thing that should have to be built to a spec is the "static site generator." The rest of it comes for "free" if you follow the spec since it's all front-end (resizer, annotations) or centralized (patterns). The generator reads in a common set of files and spits out a common set of files. Again, hence the spec.
